config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true,
  length: {maximum: 120, minimum: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    if params.has_key?('post')
      @post = Post.new(params.require(:post).permit(:content))
    else
      @post = Post.new
    end
  end

  def create
    @post = Post.new(params.require(:post).permit(:content))
    if @post.save
      redirect_to posts_path
    else render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(params.require(:post).permit(:content))

  end
  def delete
  end

  def confirm
    @post = Post.new(params.require(:post).permit(:content))
    render 'new' if @post.invalid?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/confirm.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <p>以下の内容で登録しても良いですか？</p>
  <%= form.hidden_field :content %>
  <%= @post.content %>
  <%= form.submit%>
  <%= link_to '戻る', new_post_path(params: {post: {content: @post.content}}), action: 'post' %>
<% end %>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <p>新規投稿をします</p>
  <%= form.text_area :content %>
  <%= form.submit%>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <p>ID:<%= post.id%><br>投稿の内容：<%= post.content %></p>
<% end %>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true, url: confirm_posts_path) do |form| %>
  <h3>新規投稿をします</h3>
  <% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <ul>
      <li style="color: firebrick"><%= msg %></li>
    </ul>
  <% end %>
  <% end %>
  <%= form.text_area :content %>
  <%= form.submit%>
<% end %>
<%= link_to '投稿一覧に戻る', posts_path %>